FROM swaggerapi/swagger-ui:latest

COPY /documentation/openapi.json /

ENV API_KEY="**None**" \
    SWAGGER_JSON="/openapi.json" \
    PORT=80 \
    PORT_IPV6="" \
    BASE_URL="/" \
    SWAGGER_JSON_URL=""

EXPOSE 80